export const PATHS = {
    HOME: '/',
    SIGNIN: '/signin',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    CREATE_NEW_PASSWORD: '/create-new-password',
    OTP_VERIFICATION: '/otp',
    POSTS: '/posts',
    POST_DETAIL: '/posts/:id',
    PROFILE: '/profile',
    WALLET: '/wallet',
    NOTIFICATION: '/notification',
    REWARDS: '/rewards',
    FEEDBACKS: '/feedback',
    ADMIN_FEEDBACKS: '/admin/feedback-manager',
    USER_PROFILE: '/user-profile/:id',
    ADMIN_REPORTS: '/admin/reports',
    SEARCH: '/search',
    ABOUT: '/about',
    CONTENT_POLICY: '/content-policy',
    HELP: '/help',
    EVENTS: '/events',
    EVENT_DETAIL: '/events/:id',
    BOOKMARKS: '/bookmarks',
    DEPOSIT: '/deposit',
    RECOMMENDATIONS: '/recommendations',
    EXPLORE: '/explore',
};
